apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - protocol: TCP
      nodePort: 30100
      port: 8080
      targetPort: 8080